### ISSUE TITLE
What version of PHP do you recommend?

### ISSUE THREAD

**Issue by wakiyamap** [nachat1/MonacardHub#1]
What is the recommended PHP version to run the source of this repository?

このレポジトリのソースを動かす際のPHP推奨バージョンはいくつでしょうか？

**Comment by nachat1** [comment]
Recommended version is PHP7.2.
まだ作り始めたばかりなのでほぼ何もないですが一応7.2でやっていこうと思ってます。

**Comment by wakiyamap** [comment]
Thanks for reply.
回答ありがとうございます。
