### ISSUE TITLE
`regist_time` and `update_time` are allways null.

### ISSUE THREAD

**Issue by ocknamo** [nachat1/MonacardHub#3]
I think api response of `regist_time` and `update_time`  in `card_detail` are  allways null.

Is this the correct response?

full api path: `/api/v1/card_detail.php`
sample url:  https://monacardhub.mona.jp/api/v1/card_detail.php?update_time=1518063634

I appreciate any help.

**Comment by nachat1** [comment]
Thank you.
It is bug so fix in a few days.

**Comment by nachat1** [comment]
Fixed this issue.

**Comment by nachat1** [comment]
Fixed this issue.
