### ISSUE TITLE
"tw_id" and "tw_name" are always empty string.

### ISSUE THREAD

**Issue by ocknamo** [nachat1/MonacardHub#8]
I think "tw_id" and "tw_name" are always empty string.

https://monacardhub.nachatdayo.com/api/v1/card_detail.php?update_time=1518063634

The DB does not seem to have the necessary columns.

Or are these implementations in the works?

**Comment by nachat1** [comment]
tw_id and tw_name are always empty. It is not bug and not planned to be used.
Only for card.mona.jp compatibility when called api.

**Comment by ocknamo** [comment]
I got it.Thank you.
